# Generated by Django 4.2 on 2023-05-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de area')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Primer Nombre')),
                ('second_name', models.CharField(max_length=100, verbose_name='Segundo Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('second_last_name', models.CharField(max_length=100, verbose_name='Segundo Apellido')),
                ('identity_card', models.IntegerField(verbose_name='Carnet de Identidad')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en ')),
                ('area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_survey.area')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='Codigo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en ')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Eliminado en')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='Codigo Pregunta')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_survey.employee')),
                ('id_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='Codigo de respuesta')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_survey.answeroption')),
                ('id_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_survey.evaluation')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_survey.question')),
            ],
        ),
    ]
