# Generated by Django 4.2 on 2023-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Descripcion'),
        ),
    ]
