# Generated by Django 4.2 on 2023-05-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_survey', '0002_survey_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='id_answer_option',
            new_name='answer_option',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='id_evaluation',
            new_name='evaluation',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='id_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answeroption',
            old_name='id_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='area_id',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='id_employee',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='evaluation',
            old_name='id_survey',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id_survey',
            new_name='survey',
        ),
    ]
