# Generated by Django 4.2 on 2023-05-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_survey', '0003_rename_id_answer_option_answer_answer_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures/images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='pictures/questions/'),
        ),
    ]
