# Generated by Django 4.2 on 2023-05-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_survey', '0004_employee_picture_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='questions/'),
        ),
    ]
