# Generated by Django 4.2 on 2023-05-09 19:23

import api_survey.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_survey', '0005_alter_employee_picture_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(null=True, upload_to=api_survey.utils.rename_image),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=api_survey.utils.rename_question_image),
        ),
    ]
